import type { Preset } from './types'

const commonMaterials = [
  { id: 'AIR', type: 'constant' as const, n: 1.0 },
  {
    id: 'N-BK7',
    type: 'sellmeier' as const,
    B: [1.03961212, 0.231792344, 1.01046945],
    C: [0.00600069867, 0.0200179144, 103.560653],
  },
  {
    id: 'N-F2',
    type: 'sellmeier' as const,
    B: [1.34533359, 0.209073176, 0.937357162],
    C: [0.00997743871, 0.0470450767, 111.886764],
  },
]

// Shipped presets use their centered, rotationally symmetric baseline. They
// sample the meridional theta_y direction; P003 decenter/tilt cases require
// user-supplied signed Y/Z fields for their asymmetric evaluation.
export const presets: Preset[] = [
  {
    id: 'P001',
    name: 'Ideal Thin Lens 50mm F4',
    summary: 'Thin lens baseline for paraxial, preview, spot, and focus policy checks.',
    recommendedAnalysis: ['preview', 'spot', 'paraxial'],
    recommendedFields: [
      { id: 'center', type: 'angular', theta_y_deg: 0, theta_z_deg: 0 },
      { id: 'mid-y', type: 'angular', theta_y_deg: 12.813585, theta_z_deg: 0, preset_label: 'image_height_70pct' },
      { id: 'edge-y', type: 'angular', theta_y_deg: 18, theta_z_deg: 0 },
    ],
    system: {
      name: 'P001 Ideal Thin Lens 50mm F4',
      units: 'mm',
      optical_axis: '+X',
      system_type: 'focal',
      wavelengths_nm: { primary: 587.56, samples: [587.56] },
      materials: commonMaterials,
      surfaces: [
        {
          id: 'STOP',
          kind: 'aperture_stop',
          surface_type: 'plane',
          thickness_after_mm: 0,
          semi_diameter_mm: 6.25,
          aperture: { shape: 'circle', semi_diameter_mm: 6.25 },
        },
        {
          id: 'TL1',
          kind: 'thin_lens',
          surface_type: 'plane',
          focal_length_mm: 50,
          thickness_after_mm: 50,
          semi_diameter_mm: 7,
        },
        { id: 'IMG', kind: 'sensor', surface_type: 'plane', sensor: { width_mm: 36, height_mm: 24 } },
      ],
    },
  },
  {
    id: 'P002',
    name: 'N-BK7 Biconvex Singlet 50mm Demo',
    summary: 'Simple spherical singlet for basic aberration and chromatic behavior.',
    recommendedAnalysis: ['preview', 'spot', 'chromatic'],
    recommendedFields: [
      { id: 'center', type: 'angular', theta_y_deg: 0, theta_z_deg: 0 },
      { id: 'mid-y', type: 'angular', theta_y_deg: 9.900092, theta_z_deg: 0, preset_label: 'image_height_70pct' },
      { id: 'edge-y', type: 'angular', theta_y_deg: 14, theta_z_deg: 0 },
    ],
    system: {
      name: 'P002 N-BK7 Biconvex Singlet',
      units: 'mm',
      optical_axis: '+X',
      system_type: 'focal',
      wavelengths_nm: { primary: 587.56, samples: [486.13, 587.56, 656.27] },
      materials: commonMaterials,
      surfaces: [
        {
          id: 'STOP',
          kind: 'aperture_stop',
          surface_type: 'plane',
          thickness_after_mm: 2,
          semi_diameter_mm: 8,
          aperture: { shape: 'circle', semi_diameter_mm: 8 },
        },
        { id: 'S1', kind: 'refractive', surface_type: 'spherical', radius_mm: 50, thickness_after_mm: 5, material_after: 'N-BK7', semi_diameter_mm: 9.5 },
        { id: 'S2', kind: 'refractive', surface_type: 'spherical', radius_mm: -50, thickness_after_mm: 46.5, material_after: 'AIR', semi_diameter_mm: 9.75 },
        { id: 'IMG', kind: 'sensor', surface_type: 'plane', sensor: { width_mm: 36, height_mm: 24 } },
      ],
    },
  },
  {
    id: 'P005',
    name: 'Coaxial Cassegrain Telescope Demo',
    summary: 'v2.1 corrected coaxial two-mirror telescope: EFL about 3000mm and F/15.',
    recommendedAnalysis: ['paraxial', 'preview'],
    recommendedFields: [
      { id: 'center', type: 'angular', theta_y_deg: 0, theta_z_deg: 0 },
      { id: 'mid-y', type: 'angular', theta_y_deg: 0.196001, theta_z_deg: 0, preset_label: 'image_height_70pct' },
      { id: 'edge-y', type: 'angular', theta_y_deg: 0.28, theta_z_deg: 0 },
    ],
    system: {
      name: 'P005 Coaxial Cassegrain v2.1',
      units: 'mm',
      optical_axis: '+X',
      system_type: 'focal',
      wavelengths_nm: { primary: 587.56, samples: [587.56] },
      materials: [{ id: 'AIR', type: 'constant', n: 1.0 }],
      surfaces: [
        {
          id: 'STOP',
          kind: 'aperture_stop',
          surface_type: 'plane',
          // The secondary mirror blocks the central 40 mm radius of M1.
          // Keep the stop ahead of the curved primary edge sag and visibly
          // separate from M1 in the layout without changing mirror spacing.
          thickness_after_mm: 80,
          semi_diameter_mm: 100,
          aperture: { shape: 'annulus', inner_semi_diameter_mm: 40, outer_semi_diameter_mm: 100 },
        },
        { id: 'M1', kind: 'mirror', surface_type: 'spherical', radius_mm: -2000, thickness_after_mm: -650, semi_diameter_mm: 100 },
        { id: 'M2', kind: 'mirror', surface_type: 'spherical', radius_mm: -1050, thickness_after_mm: 1050, semi_diameter_mm: 40 },
        { id: 'IMG', kind: 'sensor', surface_type: 'plane', sensor: { width_mm: 30, height_mm: 30 } },
      ],
    },
  },
  {
    id: 'P003',
    name: 'Achromat Doublet 100mm Demo',
    summary: 'BK7/F2 achromat for chromatic, ray fan, MTF, distortion, and field curvature views.',
    recommendedAnalysis: ['preview', 'ray_fan', 'mtf', 'distortion', 'field_curvature'],
    recommendedFields: [
      { id: 'center', type: 'angular', theta_y_deg: 0, theta_z_deg: 0 },
      { id: 'mid-y', type: 'angular', theta_y_deg: 7.036366, theta_z_deg: 0, preset_label: 'image_height_70pct' },
      { id: 'edge-y', type: 'angular', theta_y_deg: 10, theta_z_deg: 0 },
    ],
    system: {
      name: 'P003 Achromat Doublet 100mm',
      units: 'mm',
      optical_axis: '+X',
      system_type: 'focal',
      wavelengths_nm: { primary: 587.56, samples: [486.13, 587.56, 656.27] },
      materials: commonMaterials,
      surfaces: [
        {
          id: 'STOP',
          kind: 'aperture_stop',
          surface_type: 'plane',
          thickness_after_mm: 1.5,
          semi_diameter_mm: { variable: 'iris_radius_mm', default: 10 },
          aperture: { shape: 'circle', semi_diameter_mm: { variable: 'iris_radius_mm', default: 10 } },
        },
        { id: 'S1', kind: 'refractive', surface_type: 'spherical', radius_mm: 62.5, thickness_after_mm: 4.0, material_after: 'N-BK7', semi_diameter_mm: 11.5 },
        { id: 'S2', kind: 'refractive', surface_type: 'spherical', radius_mm: -43.0, thickness_after_mm: 2.0, material_after: 'N-F2', semi_diameter_mm: 11.75 },
        { id: 'S3', kind: 'refractive', surface_type: 'spherical', radius_mm: -125.0, thickness_after_mm: 96.0, material_after: 'AIR', semi_diameter_mm: 12 },
        { id: 'IMG', kind: 'sensor', surface_type: 'plane', sensor: { width_mm: 36, height_mm: 24 } },
      ],
      groups: [
        { id: 'FOCUS_G', name: 'Focus group', from_surface: 'S1', to_surface: 'S3' },
        { id: 'OIS_G', name: 'OIS decenter/tilt group', from_surface: 'S1', to_surface: 'S3' },
      ],
      zoom_positions: [
        { id: 'infinity', focal_length_nominal_mm: 100, group_positions: { FOCUS_G: { shift_x_mm: 0 } } },
        { id: 'close_focus', focal_length_nominal_mm: 100, group_positions: { FOCUS_G: { shift_x_mm: 2 } } },
      ],
    },
  },
  {
    id: 'P006',
    name: 'Keplerian Afocal Telescope Demo',
    summary: 'Afocal telescope with an eye_reference terminal plane; image-plane policy controls are intentionally disabled.',
    recommendedAnalysis: ['afocal', 'exit_pupil', 'telescope'],
    recommendedFields: [
      { id: 'center', type: 'angular', theta_y_deg: 0, theta_z_deg: 0 },
      { id: 'mid-y', type: 'angular', theta_y_deg: 0.5, theta_z_deg: 0 },
      { id: 'edge-y', type: 'angular', theta_y_deg: 1, theta_z_deg: 0 },
    ],
    system: {
      name: 'P006 Keplerian Afocal Telescope',
      units: 'mm',
      optical_axis: '+X',
      system_type: 'afocal',
      wavelengths_nm: { primary: 587.56, samples: [587.56] },
      materials: [{ id: 'AIR', type: 'constant', n: 1.0 }],
      surfaces: [
        {
          id: 'STOP',
          kind: 'aperture_stop',
          surface_type: 'plane',
          thickness_after_mm: 0,
          semi_diameter_mm: 25,
          aperture: { shape: 'circle', semi_diameter_mm: 25 },
        },
        { id: 'OBJ', kind: 'thin_lens', surface_type: 'plane', focal_length_mm: 100, thickness_after_mm: 120, semi_diameter_mm: 25 },
        { id: 'EYEPIECE', kind: 'thin_lens', surface_type: 'plane', focal_length_mm: 20, thickness_after_mm: 20, semi_diameter_mm: 10 },
        { id: 'EYE', kind: 'eye_reference', surface_type: 'plane', eye: { pupil_diameter_mm: 4, position_mode: 'fixed_offset' } },
      ],
      groups: [
        { id: 'EYE_G', from_surface: 'EYE', to_surface: 'EYE' },
        { id: 'FOCUS', from_surface: 'EYEPIECE', to_surface: 'EYEPIECE' },
      ],
    },
  },
    {
      id: 'P007',
    name: 'Fast Positive-Negative Meniscus Pair 50mm Demo',
    summary: 'Fast F/1.8 two-group meniscus pair for checking strong positive and negative curvature in the layout view.',
    recommendedAnalysis: ['preview', 'spot', 'ray_fan', 'paraxial'],
    recommendedFields: [
      { id: 'center', type: 'angular', theta_y_deg: 0, theta_z_deg: 0 },
      { id: 'mid-y', type: 'angular', theta_y_deg: 1.050122, theta_z_deg: 0, preset_label: 'image_height_70pct' },
      { id: 'edge-y', type: 'angular', theta_y_deg: 1.5, theta_z_deg: 0 },
    ],
    system: {
      name: 'P007 Fast Positive-Negative Meniscus Pair 50mm',
      units: 'mm',
      optical_axis: '+X',
      system_type: 'focal',
      wavelengths_nm: { primary: 587.56, samples: [486.13, 587.56, 656.27] },
      materials: commonMaterials,
      surfaces: [
          { id: 'S1', kind: 'refractive', surface_type: 'spherical', radius_mm: 15.0, thickness_after_mm: 10.5, material_after: 'N-BK7', semi_diameter_mm: 14.5 },
          { id: 'S2', kind: 'refractive', surface_type: 'spherical', radius_mm: 60.0, thickness_after_mm: 3.0, material_after: 'AIR', semi_diameter_mm: 14.5 },
        {
          id: 'STOP',
          kind: 'aperture_stop',
          surface_type: 'plane',
          thickness_after_mm: 3.0,
          semi_diameter_mm: 13.2,
          aperture: { shape: 'circle', semi_diameter_mm: 13.2 },
        },
        { id: 'S3', kind: 'refractive', surface_type: 'spherical', radius_mm: -35.0, thickness_after_mm: 3.0, material_after: 'N-F2', semi_diameter_mm: 14.25 },
          { id: 'S4', kind: 'refractive', surface_type: 'spherical', radius_mm: -100.0, thickness_after_mm: 26.948477258301352, material_after: 'AIR', semi_diameter_mm: 15 },
        { id: 'IMG', kind: 'sensor', surface_type: 'plane', sensor: { width_mm: 36, height_mm: 24 } },
      ],
      },
    },
    {
      id: 'P008',
      name: 'Real Achromatic Keplerian Telescope Demo',
      summary: 'Afocal telescope built from BK7/F2 achromatic doublets with real spherical refracting surfaces.',
      recommendedAnalysis: ['afocal', 'exit_pupil', 'telescope', 'preview'],
      recommendedFields: [
        { id: 'center', type: 'angular', theta_y_deg: 0, theta_z_deg: 0 },
        { id: 'mid-y', type: 'angular', theta_y_deg: 0.25, theta_z_deg: 0 },
        { id: 'edge-y', type: 'angular', theta_y_deg: 0.5, theta_z_deg: 0 },
      ],
      system: {
        name: 'P008 Real Achromatic Keplerian Telescope',
        units: 'mm',
        optical_axis: '+X',
        system_type: 'afocal',
        wavelengths_nm: { primary: 587.56, samples: [486.13, 587.56, 656.27] },
        materials: commonMaterials,
        surfaces: [
          {
            id: 'STOP',
            kind: 'aperture_stop',
            surface_type: 'plane',
            thickness_after_mm: 1.5,
            semi_diameter_mm: 6,
            aperture: { shape: 'circle', semi_diameter_mm: 6 },
          },
          { id: 'O1', kind: 'refractive', surface_type: 'spherical', radius_mm: 62.5, thickness_after_mm: 4.0, material_after: 'N-BK7', semi_diameter_mm: 12 },
          { id: 'O2', kind: 'refractive', surface_type: 'spherical', radius_mm: -43.0, thickness_after_mm: 2.0, material_after: 'N-F2', semi_diameter_mm: 12 },
          { id: 'O3', kind: 'refractive', surface_type: 'spherical', radius_mm: -125.0, thickness_after_mm: 108.51795245333561, material_after: 'AIR', semi_diameter_mm: 12 },
          { id: 'E1', kind: 'refractive', surface_type: 'spherical', radius_mm: 25.0, thickness_after_mm: 0.4, material_after: 'N-F2', semi_diameter_mm: 6 },
          { id: 'E2', kind: 'refractive', surface_type: 'spherical', radius_mm: 8.6, thickness_after_mm: 0.8, material_after: 'N-BK7', semi_diameter_mm: 6 },
          { id: 'E3', kind: 'refractive', surface_type: 'spherical', radius_mm: -12.5, thickness_after_mm: 20.0, material_after: 'AIR', semi_diameter_mm: 6 },
          { id: 'EYE', kind: 'eye_reference', surface_type: 'plane', eye: { pupil_diameter_mm: 5, position_mode: 'fixed_offset' } },
        ],
        groups: [
          { id: 'EYE_G', from_surface: 'EYE', to_surface: 'EYE' },
          { id: 'FOCUS', from_surface: 'E1', to_surface: 'E3' },
        ],
      },
    },
    {
      id: 'P009',
      name: 'N-BK7 Aspheric Singlet 50mm Demo',
      summary: 'P002-derived singlet with an even-aspheric front surface for direct spherical-aberration comparison.',
      recommendedAnalysis: ['preview', 'spot', 'ray_fan', 'paraxial'],
      recommendedFields: [
        { id: 'center', type: 'angular', theta_y_deg: 0, theta_z_deg: 0 },
        { id: 'mid-y', type: 'angular', theta_y_deg: 9.900092, theta_z_deg: 0, preset_label: 'image_height_70pct' },
        { id: 'edge-y', type: 'angular', theta_y_deg: 14, theta_z_deg: 0 },
      ],
      system: {
        name: 'P009 N-BK7 Aspheric Singlet',
        units: 'mm',
        optical_axis: '+X',
        system_type: 'focal',
        wavelengths_nm: { primary: 587.56, samples: [486.13, 587.56, 656.27] },
        materials: commonMaterials,
        surfaces: [
          {
            id: 'STOP',
            kind: 'aperture_stop',
            surface_type: 'plane',
            thickness_after_mm: 2,
            semi_diameter_mm: 8,
            aperture: { shape: 'circle', semi_diameter_mm: 8 },
          },
          {
            id: 'ASP1',
            kind: 'refractive',
            surface_type: 'aspherical_even',
            radius_mm: 50,
            conic: -1.1792,
            asphere_coefficients: { A4: -0.0000024992 },
            thickness_after_mm: 5,
            material_after: 'N-BK7',
            semi_diameter_mm: 9.5,
          },
          { id: 'S2', kind: 'refractive', surface_type: 'spherical', radius_mm: -50, thickness_after_mm: 46.9248, material_after: 'AIR', semi_diameter_mm: 9.75 },
          { id: 'IMG', kind: 'sensor', surface_type: 'plane', sensor: { width_mm: 36, height_mm: 24 } },
        ],
      },
    },
    {
      id: 'P010',
      name: 'High-Order Aspheric Singlet Inflection Demo',
      summary: 'Strong A4/A6/A8 terms create two radial curvature reversals for high-order asphere inspection.',
      recommendedAnalysis: ['preview', 'spot', 'ray_fan', 'paraxial'],
      recommendedFields: [
        { id: 'center', type: 'angular', theta_y_deg: 0, theta_z_deg: 0 },
        { id: 'mid-y', type: 'angular', theta_y_deg: 6.68117, theta_z_deg: 0, preset_label: 'image_height_70pct' },
        { id: 'edge-y', type: 'angular', theta_y_deg: 9.5, theta_z_deg: 0 },
      ],
      system: {
        name: 'P010 High-Order Aspheric Singlet',
        units: 'mm',
        optical_axis: '+X',
        system_type: 'focal',
        wavelengths_nm: { primary: 587.56, samples: [486.13, 587.56, 656.27] },
        materials: commonMaterials,
        surfaces: [
          {
            id: 'STOP',
            kind: 'aperture_stop',
            surface_type: 'plane',
            thickness_after_mm: 2,
            semi_diameter_mm: 8,
            aperture: { shape: 'circle', semi_diameter_mm: 8 },
          },
          {
            id: 'ASP1',
            kind: 'refractive',
            surface_type: 'aspherical_even',
            radius_mm: 50,
            conic: -1,
            asphere_coefficients: { A4: -0.0001, A6: 0.0000005, A8: -0.0000000005 },
            thickness_after_mm: 5,
            material_after: 'N-BK7',
            semi_diameter_mm: 9.5,
          },
          { id: 'S2', kind: 'refractive', surface_type: 'spherical', radius_mm: -50, thickness_after_mm: 63.175, material_after: 'AIR', semi_diameter_mm: 9.75 },
          { id: 'IMG', kind: 'sensor', surface_type: 'plane', sensor: { width_mm: 36, height_mm: 24 } },
        ],
      },
    },
  ]

export const visualFixturePresets: Preset[] = [
  {
    id: 'F_ASPHERE',
    name: 'Asphere Layout Visual Fixture',
    summary: 'Development-only fixture for comparing spherical and even-aspheric sag in the layout view.',
    recommendedAnalysis: ['layout'],
    system: {
      name: 'Asphere Layout Visual Fixture',
      units: 'mm',
      optical_axis: '+X',
      system_type: 'focal',
      wavelengths_nm: { primary: 587.56, samples: [587.56] },
      materials: commonMaterials,
      surfaces: [
        {
          id: 'STOP',
          kind: 'aperture_stop',
          surface_type: 'plane',
          thickness_after_mm: 4,
          semi_diameter_mm: 8,
          aperture: { shape: 'circle', semi_diameter_mm: 8 },
        },
        { id: 'SPH', kind: 'refractive', surface_type: 'spherical', radius_mm: 32.5, thickness_after_mm: 7, material_after: 'N-BK7', semi_diameter_mm: 15 },
        {
          id: 'ASP',
          kind: 'refractive',
          surface_type: 'aspherical_even',
          radius_mm: 32.5,
          conic: -1,
          asphere_coefficients: { A4: 0.00003 },
          thickness_after_mm: 46,
          material_after: 'AIR',
          semi_diameter_mm: 15,
        },
        { id: 'IMG', kind: 'sensor', surface_type: 'plane', sensor: { width_mm: 36, height_mm: 24 } },
      ],
    },
  },
  {
    id: 'F_EDGE_CASE',
    name: 'Layout Edge Case Fixture',
    summary: 'Development-only fixture for plane boundaries and edge-thickness warning rendering.',
    recommendedAnalysis: ['layout'],
    system: {
      name: 'Layout Edge Case Fixture',
      units: 'mm',
      optical_axis: '+X',
      system_type: 'focal',
      wavelengths_nm: { primary: 587.56, samples: [587.56] },
      materials: commonMaterials,
      surfaces: [
        {
          id: 'STOP',
          kind: 'aperture_stop',
          surface_type: 'plane',
          thickness_after_mm: 4,
          semi_diameter_mm: 8,
          aperture: { shape: 'circle', semi_diameter_mm: 8 },
        },
        { id: 'PP1', kind: 'refractive', surface_type: 'plane', thickness_after_mm: 2, material_after: 'N-BK7', semi_diameter_mm: 12 },
        { id: 'PP2', kind: 'refractive', surface_type: 'plane', thickness_after_mm: 10, material_after: 'AIR', semi_diameter_mm: 12 },
        { id: 'PS1', kind: 'refractive', surface_type: 'plane', thickness_after_mm: -2, material_after: 'N-BK7', semi_diameter_mm: 12 },
        { id: 'PS2', kind: 'refractive', surface_type: 'spherical', radius_mm: -24, thickness_after_mm: 42, material_after: 'AIR', semi_diameter_mm: 10 },
        { id: 'IMG', kind: 'sensor', surface_type: 'plane', sensor: { width_mm: 36, height_mm: 24 } },
      ],
    },
  },
]
